StripeApp/Models/stripeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StripeApp.Models
{
    public class stripeModel
    {
       
        public string StripePublishableKey { get; set; }
        public string StripeToken { get; set; }
        public string StripeEmail { get; set; }
        public string IntentSecretis { get; set; }
        public string IntentId { get; set; }
        public string fullName { get; set; }
        public string PlanId { get; set; }


    }
}

StripeApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StripeApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

StripeApp/Controllers/signUpController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Stripe;
using StripeApp.Models;

namespace StripeApp.Controllers
{
    public class signUpController : Controller
    {
        // GET: signUp
        public ActionResult Index()
        {
            string stripePublishableKey = ConfigurationManager.AppSettings["stripePublishableKey"];
            var model = new stripeModel() { StripePublishableKey = stripePublishableKey, PlanId = "basicMonthly", PlanCost = "100", PaymentFormHidden = true };
            return View(model);
        }
        [HttpPost]
        public ActionResult Index(stripeModel  model)
        {
            var customers = new CustomerService();

            var customer = customers.Create(new CustomerCreateOptions
            {
                Email = model.StripeEmail,
                Source = model.StripeToken,
                Name = model.fullName,

            });
            var subscriptionOptions = new SubscriptionCreateOptions()
            {
                PlanId = model.PlanId,
                CustomerId = customer.Id,
                TrialFromPlan = false,
                Expand = new List<string> { "latest_invoice.payment_intent", "pending_setup_intent" },
            };

            var subscriptionService = new SubscriptionService();
            Subscription subscription = subscriptionService.Create(subscriptionOptions);


            if (subscription.LatestInvoice.PaymentIntent.NextAction != null)
            {
                if (subscription.LatestInvoice.PaymentIntent.Status == "requires_action")
                {
                    
                    model.IntentSecretis = subscription.LatestInvoice.PaymentIntent.ClientSecret;
                    
                }



            }
            else
            {
                return RedirectToAction("Index", "Home");
            }



            return View(model);
        }


    }
}

StripeApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

StripeApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

StripeApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

StripeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StripeApp/Views/signUp/Index.cshtml
@model StripeApp.Models.stripeModel
@{
    ViewBag.Title = "Index";
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <h2>sign up</h2>

    @if (Model.IntentSecretis == null)
    {


        <div class="main-content">
            <div class="container">

                <div class="row">


                    <div class="col-md-12">
                        <div id="payment-form-container" class="col-md-6 well" style="background-color:#fff !important;">

                            @using (Html.BeginForm("Index", "signUp", FormMethod.Post, new { id = "stripeForm", @class = "cardInfo", accept_charset = "UTF-8", novalidate = "", autocomplete = "on" }))
                            {
                                @Html.AntiForgeryToken()

                                <div class="row">

                                    <div id="card-element">
                                        <!-- A Stripe Element will be inserted here. -->
                                    </div>
                                    <div id="card-errors" role="alert"></div>

                                </div>

                                <div class="form-group">
                                    
                                        <input id="fullName" type="text" name="fullName" value="@Model.fullName" class="input-lg form-control " placeholder="Full Name" required>

                                </div>

                                <div class="form-group">
                                    
                                        <input id="email" type="email" name="stripeEmail" value="@Model.StripeEmail" class="input-lg form-control email" placeholder="Email" required>

                                </div>

                                @Html.HiddenFor(m => m.StripePublishableKey)
                                
                                <div class="row">
                                    <div class="form-group col-md-6  ">
                                        <button type="submit"  id="card-button" class="btn btn-success  btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> Subscribe</button>
                                    </div>
                                </div>

                            }

                        </div>





                    </div>

                </div>
            </div>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
        <script type="text/javascript">

            var stripe = Stripe('@Model.StripePublishableKey');
            var cardButton = document.getElementById('card-button');
            var clientSecret = cardButton.dataset.secret;
            $(function () {
                var elements = stripe.elements();
                var style = {
                    base: {
                        color: 'black',
                    },
                    invalid: {
                        color: 'red',
                    }
                };
                var card = elements.create('card', { style: style });
                // Add an instance of the card Element into the `card-element` <div>.
                card.mount('#card-element');
                // Handle real-time validation errors from the card Element.
                card.addEventListener('change', function (event) {
                    var displayError = document.getElementById('card-errors');
                    if (event.error) {
                        displayError.textContent = event.error.message;
                    } else {
                        displayError.textContent = '';
                    }
                });
                var form = document.getElementById('stripeForm');
                form.addEventListener('submit', function (event) {
                    event.preventDefault();
                    stripe.createToken(card).then(function (result) {
                        if (result.error) {
                            // Inform the user if there was an error.
                            var errorElement = document.getElementById('card-errors');
                            errorElement.textContent = result.error.message;
                        } else {
                            // Send the token to the server.
                            stripeTokenHandler(result.token);
                        }
                    });
                });
                // Submit the form with the token ID.
                function stripeTokenHandler(token) {
                    // Insert the token ID into the form so it gets submitted to the server
                    var form = document.getElementById('stripeForm');
                    var hiddenInput = document.createElement('input');
                    hiddenInput.setAttribute('type', 'hidden');
                    hiddenInput.setAttribute('name', 'stripeToken');
                    hiddenInput.setAttribute('value', token.id);
                    form.appendChild(hiddenInput);
                    // Submit the form
                    form.submit();
                }
            });


        </script>
    }

    @if (Model.IntentSecretis != null)
    {


        <div class="main-content">
            <div class="container">

                <div class="row">


                    <div class="col-md-12">
                        <div id="payment-form-container" class="col-md-6 well" style="background-color:#fff !important;">

                            @using (Html.BeginForm("Index", "signUp", FormMethod.Post, new { id = "stripeForm", @class = "cardInfo", accept_charset = "UTF-8", novalidate = "", autocomplete = "on" }))
                            {
                                @Html.AntiForgeryToken()

                                <div class="row">

                                    <div id="card-element">
                                        <!-- A Stripe Element will be inserted here. -->
                                    </div>
                                    <div id="card-errors" role="alert"></div>

                                </div>

                                <div class="form-group">
                                        <input id="fullName" type="text" name="fullName" value="@Model.fullName" class="input-lg form-control " placeholder="Full Name" required>

                                </div>

                                <div class="form-group">
                                    
                                        <input id="email" type="email" name="stripeEmail" value="@Model.StripeEmail" class="input-lg form-control email" placeholder="Email" required>

                                </div>

                                @Html.HiddenFor(m => m.StripePublishableKey)
                                
                                <div class="row">
                                    <div class="form-group col-md-6  ">
                                        <button type="submit" data-secret="@Model.IntentSecretis" id="card-button" class="btn btn-success  btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> Subscribe</button>
                                    </div>
                                </div>

                            }

                        </div>





                    </div>

                </div>
            </div>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
        <script type="text/javascript">

            var stripe = Stripe('@Model.StripePublishableKey');
            var cardButton = document.getElementById('card-button');
            var clientSecret = cardButton.dataset.secret;
            $(function() {
                // Create an instance of Elements.
                var elements = stripe.elements();
                // Custom styling can be passed to options when creating an Element.
                var style = {
                    base: {
                        color: 'black',
                    },
                    invalid: {
                        color: 'red',
                    }
                };
                // Create an instance of the card Element.
                var cardElement = elements.create('card', { style: style });
                // Add an instance of the card Element into the `card-element` <div>.
                cardElement.mount('#card-element');
                // Handle real-time validation errors from the card Element.
                cardElement.addEventListener('change',
                    function(event) {
                        var displayError = document.getElementById('card-errors');
                        if (event.error) {
                            displayError.textContent = event.error.message;
                        } else {
                            displayError.textContent = '';
                        }
                    });
                var form = document.getElementById('stripeForm');
                form.addEventListener('submit',
                    function(event) {
                        event.preventDefault();
                        stripe.handleCardPayment(clientSecret, cardElement).then(function(result) {
                            if (result.error) {
                                alert("Payment Failed" + " " + result.message);
                            } else {
                                alert("Payment is successfull.");
                            }
                        });
                    });
            });


        </script>
    }
</body>
</html>